[package]
name = "rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cxx = "1.0"            # for the Rust side bridging

[build-dependencies]
cxx-build = "1.0"      # used in build.rs to generate bridging .cc from Rust
