[package]
name = "rust_calculator"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_calculator"
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "calculator_main"
path = "src/main.rs"

[dependencies]
libc = "0.2.169"
